
ALTER TABLE public.distributions
  ADD COLUMN IF NOT EXISTS cod_processo integer,
  ADD COLUMN IF NOT EXISTS cod_escritorio integer,
  ADD COLUMN IF NOT EXISTS instancia integer,
  ADD COLUMN IF NOT EXISTS sigla_sistema text,
  ADD COLUMN IF NOT EXISTS comarca text,
  ADD COLUMN IF NOT EXISTS orgao_julgador text,
  ADD COLUMN IF NOT EXISTS tipo_do_processo text,
  ADD COLUMN IF NOT EXISTS data_audiencia timestamptz,
  ADD COLUMN IF NOT EXISTS tipo_audiencia text,
  ADD COLUMN IF NOT EXISTS valor_da_causa text,
  ADD COLUMN IF NOT EXISTS assuntos jsonb,
  ADD COLUMN IF NOT EXISTS magistrado text,
  ADD COLUMN IF NOT EXISTS autor jsonb,
  ADD COLUMN IF NOT EXISTS reu jsonb,
  ADD COLUMN IF NOT EXISTS outros_envolvidos jsonb,
  ADD COLUMN IF NOT EXISTS advogados jsonb,
  ADD COLUMN IF NOT EXISTS movimentos jsonb,
  ADD COLUMN IF NOT EXISTS documentos_iniciais jsonb,
  ADD COLUMN IF NOT EXISTS lista_documentos jsonb,
  ADD COLUMN IF NOT EXISTS cidade text,
  ADD COLUMN IF NOT EXISTS uf varchar(2),
  ADD COLUMN IF NOT EXISTS cod_pre_cadastro_termo integer,
  ADD COLUMN IF NOT EXISTS nome_pesquisado text,
  ADD COLUMN IF NOT EXISTS processo_originario text;
