
ALTER TABLE public.publications
  ADD COLUMN IF NOT EXISTS hash_publicacao text,
  ADD COLUMN IF NOT EXISTS cod_escritorio integer,
  ADD COLUMN IF NOT EXISTS data_vsap timestamptz,
  ADD COLUMN IF NOT EXISTS data_disponibilizacao timestamptz,
  ADD COLUMN IF NOT EXISTS vara text,
  ADD COLUMN IF NOT EXISTS comarca text,
  ADD COLUMN IF NOT EXISTS orgao text,
  ADD COLUMN IF NOT EXISTS nome_caderno text,
  ADD COLUMN IF NOT EXISTS sigla_diario text,
  ADD COLUMN IF NOT EXISTS esfera_diario text,
  ADD COLUMN IF NOT EXISTS num_edicao text,
  ADD COLUMN IF NOT EXISTS num_processo text,
  ADD COLUMN IF NOT EXISTS id_nome integer,
  ADD COLUMN IF NOT EXISTS cod_mapa_diario integer,
  ADD COLUMN IF NOT EXISTS nome_pesquisado text,
  ADD COLUMN IF NOT EXISTS termo_pesquisado text,
  ADD COLUMN IF NOT EXISTS oab text,
  ADD COLUMN IF NOT EXISTS estado text,
  ADD COLUMN IF NOT EXISTS uf varchar(2),
  ADD COLUMN IF NOT EXISTS area integer,
  ADD COLUMN IF NOT EXISTS perfil_contratante text,
  ADD COLUMN IF NOT EXISTS outros_termos text,
  ADD COLUMN IF NOT EXISTS controle_pg integer,
  ADD COLUMN IF NOT EXISTS complemento boolean,
  ADD COLUMN IF NOT EXISTS tipo_fonte_conteudo integer;
